conan_db_app/urls.py
from django.urls import path

from . import views

app_name = 'conan_db_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('chara_list/', views.CharaListView.as_view(), name='list'),
    path('chara_detail/<int:pk>/', views.chara_detail_func, name='detail'),
    path('chara_detail/<int:pk>/<int:page>/', views.chara_detail_func, name='detail'),
    path('affiliation_list/', views.AffiliationListView.as_view(), name='affiliation_list'),
    path('affiliation_detail/<int:pk>/', views.AffiliationDetailView.as_view(), name='affiliation_detail'),
    path('case_list/', views.CaseListView.as_view(), name='case_list'),
    path('case_list/<int:page>/', views.CaseListView.as_view(), name='case_list'),
    path('case_detail/<int:pk>/', views.CaseDetailView.as_view(), name='case_detail'),
    path('wiseword_list/', views.WisewordListView.as_view(), name='wiseword_list'),
    path('wiseword_list/<int:page>/', views.WisewordListView.as_view(), name='wiseword_list'),
    path('question_create/', views.QuestionCreateView.as_view(), name='question_create'),
    # path('question_list/<int:page>/', views.QuestionListView.as_view(), name='question_list'),
    path('question_list/', views.QuestionListView.as_view(), name='question_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conan_db/', include('conan_db_app.urls')),
]

conan_db_app/models.py
from django.db import models

# Create your models here.

class Volume(models.Model):
    number = models.IntegerField(primary_key=True)
    complement = models.TextField(blank=True, null=True)

    ### object 自体の表示方法を指定
    def __str__(self):
        return f'Volume.{self.number}'

    ### 並び順を指定
    class Meta:
        ordering = ('number',)

class CaseKind(models.Model):
    name = models.CharField(max_length=30)

    ### object 自体の表示方法を指定
    def __str__(self):
        return self.name

class Case(models.Model):
    number = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30)
    complement = models.TextField(blank=True, null=True)

    ### 他のテーブルとの関連
    kind = models.ManyToManyField(CaseKind, blank=True)

    ### object 自体の表示方法を指定
    def __str__(self):
        return f'Case.{self.number} : {self.name}'

    ### 並び順を指定
    class Meta:
        ordering = ('number',)

class Chapter(models.Model):
    name = models.CharField(max_length=30)
    number_in_volume = models.IntegerField()
    number_in_all = models.IntegerField()
    complement = models.TextField(blank=True, null=True)

    ### 他のテーブルとの関連
    volume = models.ForeignKey(Volume, on_delete=models.PROTECT, default=1)
    case = models.ForeignKey(Case, on_delete=models.PROTECT, default=1)

    ### object 自体の表示方法を指定
    def __str__(self):
        return f'Volume.{self.volume.number} - File.{self.number_in_volume}\
            ({self.number_in_all}) : {self.name}'

    ### 並び順を指定
    class Meta:
        ordering = ('number_in_all',)

class Event(models.Model):
    content = models.TextField(null=True)

    ### 他のテーブルとの関連
    chapter = models.ForeignKey(Chapter, on_delete=models.PROTECT, default=1)

    ### object 自体の表示方法を指定
    def __str__(self):
        return f'{self.content[0:15]} ...'

class Affiliation(models.Model):
    name = models.CharField(max_length=30)

    ### object 自体の表示方法を指定
    def __str__(self):
        return self.name

class Profession(models.Model):
    name = models.CharField(max_length=30)

    ### 他のテーブルとの関連
    affiliation = models.ForeignKey(Affiliation, on_delete=models.PROTECT, blank=True, null=True)

    ### object 自体の表示方法を指定
    def __str__(self):
        if self.affiliation:
            return f'{self.affiliation.name} -- {self.name}'
        else:
            return f'None -- {self.name}'


class Character(models.Model):
    name = models.CharField(max_length=30)
    skill = models.CharField(blank=True, null=True, max_length=200)
    complement = models.TextField(blank=True, null=True)
    # 付与する情報の例。
    # 登場の仕方（実際に登場するのではなく、会話中で名前が出てくる。思考や回想シーンの中で登場する。）
    # 同一人物の紹介。
    # 等々。
    
    ### 他のテーブルとの関連
    chapter = models.ManyToManyField(Chapter)
    event_related_to = models.ManyToManyField(Event, blank=True)
    belong_to = models.ManyToManyField(Affiliation, blank=True)
    profession = models.ManyToManyField(Profession, blank=True)

    ### object 自体の表示方法を指定
    def __str__(self):
        return f'<ID = {self.id}> {self.name}'

    ### 並び順を指定
    class Meta:
        ordering = ('id',)

class Wiseword(models.Model):
    content = models.CharField(max_length=200)

    ### 他のテーブルとの関連
    chapter = models.ForeignKey(Chapter, on_delete=models.PROTECT, default=1)
    character = models.ForeignKey(Character, on_delete=models.PROTECT, default=1)

    ### object 自体の表示方法を指定
    def __str__(self):
        return f'{self.character.name} --- {self.content[0:15]}'

class Question(models.Model):
    KIND_OF_QUESTION=[
        ( 'question', '問題'),
        ( 'questionnaire', 'アンケート'),
    ]

    JENRE_OF_QUESTION=[
        ( 'conan', '名探偵コナン関係'),
        ( 'others', 'それ以外'),
    ]

    NUMBER_OF_ANSWER_OPTION=[
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
    ]
    
    kind = models.CharField(max_length=20, blank=False, null=False, choices=KIND_OF_QUESTION, default='question')
    jenre = models.CharField(max_length=20, blank=False, null=False, choices=JENRE_OF_QUESTION, default='conan') 
    content = models.TextField(blank=False, null=False)
    n_option = models.IntegerField(blank=False, null=False, choices=NUMBER_OF_ANSWER_OPTION)
    option1 = models.TextField(blank=False, null=False) 
    option2 = models.TextField(blank=False, null=False)
    option3 = models.TextField(blank=True, null=True)
    option4 = models.TextField(blank=True, null=True)
    option5 = models.TextField(blank=True, null=True)
    
    

conan_db_app/forms.py
from django import forms
from .models import Question, CaseKind, Volume, Character

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['jenre', 'kind','content','n_option','option1','option2','option3','option4','option5']

    def clean_option1(self):
        option1 = self.cleaned_data["option1"]
        option1_min = 10
        if len(option1) < option1_min:
            raise forms.ValidationError(f'{option1_min}文字以上入力してください。')
        
        return option1    

class RefineQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['jenre', 'kind']
        widgets = {
            'kind': forms.RadioSelect(),
            'jenre': forms.RadioSelect()
        }

class WithEventForm(forms.Form):
    with_event = forms.BooleanField(label='重要なイベントのみを表示する', required=False)

class WithEventForm2(forms.Form):
    with_event2 = forms.BooleanField(label='重要なイベントのみを表示する', required=False)

class CaseKindForm(forms.Form):
    CASE_KIND = [(i_kind.name, i_kind.name) for i_kind in CaseKind.objects.all()]
    case_kind = forms.MultipleChoiceField(choices=CASE_KIND, required=False,\
        widget=forms.CheckboxSelectMultiple(), label='事件の種類で絞り込む')

class VolumeForm(forms.Form):
    VOL_LIST = [(i_vol.number, i_vol.number) for i_vol in Volume.objects.all()]
    volume = forms.MultipleChoiceField(choices=VOL_LIST, required=False,\
        widget=forms.CheckboxSelectMultiple(), label='巻数で絞り込む')

class CharaForm(forms.Form):
    CHARA_LIST = [(i_chara.name, i_chara.name) for i_chara in Character.objects.all()]
    character = forms.MultipleChoiceField(choices=CHARA_LIST, required=False,\
        widget=forms.CheckboxSelectMultiple(), label='人物で絞り込む')

class CaseNameForm(forms.Form):
    case_name = forms.CharField(max_length=30, required=False,\
        label='事件名で絞り込む(部分一致 : 最長 30 文字)')

class WisewordForm(forms.Form):
    wiseword_char = forms.CharField(max_length=100, required=False,\
        label='事件名で絞り込む(部分一致 : 最長 100 文字)')

conan_db_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.views.generic.edit import FormMixin
from .models import Character, Chapter, Question, Affiliation, Case, Wiseword
from .forms import QuestionForm, RefineQuestionForm, WithEventForm,\
    CaseKindForm, VolumeForm, CharaForm, CaseNameForm, WisewordForm
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib import messages  # メッセージフレームワーク

# Create your views here.

class IndexView(TemplateView):        

    def get(self, request):
        return render(request, 'conan_db_app/index.html')


class CharaListView(ListView):
    model = Character


class AffiliationListView(ListView):
    model = Affiliation


class AffiliationDetailView(DetailView):
    model = Affiliation


class WisewordListView(ListView, FormMixin):
    model = Wiseword
    paginate_by = 3
    form_class = CharaForm

    def post(self, request, page = None):
        return self.get(request)

    def get_context_data(self, **kwargs):
        form_list = {
            'form1': WisewordForm(**self.get_form_kwargs()),
        }
        kwargs.update(form_list)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        # 各絞り込みに当てはまる事件の番号の集合を記録
        refined_wiseword_number_list = []

        # 名言をキャラクターについて or 検索
        if chara_list := self.request.POST.getlist('character'):       
            tmp = set()
            for i_wiseword in Wiseword.objects.all():
                if any([ j_chara == i_wiseword.character.name for j_chara in chara_list]):
                    tmp.add(i_wiseword.id)
            refined_wiseword_number_list.append(tmp)

        # 名言の内容による絞り込みがあれば当てはまる事件の番号の集合を
        # 集合のリスト refined_case_number_list に登録    
        if wiseword_char := self.request.POST.get('wiseword_char'):
            wiseword_char_list = wiseword_char.split()
            if not wiseword_char_list:
                pass
            else:
                tmp = set()
                for i, i_wiseword_char in enumerate(wiseword_char_list, 1):
                    if i == 1:
                        tmp = {i_wiseword.id for i_wiseword in Wiseword.objects.filter(content__contains=str(i_wiseword_char))}
                    else:
                        tmp &= {i_wiseword.id for i_wiseword in Wiseword.objects.filter(content__contains=str(i_wiseword_char))}
                refined_wiseword_number_list.append(tmp)

        if refined_wiseword_number_list:
            for i, i_refined_set in enumerate(refined_wiseword_number_list, 1):
                if i == 1:
                    and_refined_set = i_refined_set
                else:
                    and_refined_set &= i_refined_set
            queryset = Wiseword.objects.filter(id__in=and_refined_set)
            
        else :
            queryset = Wiseword.objects.all()

        return queryset

class CaseListView(ListView, FormMixin):
    model = Case
    paginate_by = 3
    form_class = WithEventForm

    def get_queryset(self):
        # 各絞り込みに当てはまる事件の番号の集合を記録
        refined_case_number_list = []
        
        # 重要な出来事がに対する絞り込みがあれば当てはまる事件の番号の集合を
        # 集合のリスト refined_case_number_list に登録    
        if self.request.POST.get('with_event'):
            tmp = set()
            for i_case in Case.objects.all():
                for i_chapter in i_case.chapter_set.all():
                    if i_chapter.event_set.all():
                        tmp.add(i_case.number)
            refined_case_number_list.append(tmp)            

        # 事件の種類による絞り込みがあれば当てはまる事件の番号の集合を
        # 集合のリスト refined_case_number_list に登録    
        if kind_list := self.request.POST.getlist('case_kind'):       
            tmp = set()
            for i_case in Case.objects.all():
                kind_list_i_case = [ i_kind.name for i_kind in i_case.kind.all()]
                if all([ j_kind in kind_list_i_case for j_kind in kind_list]):
                    tmp.add(i_case.number)
            refined_case_number_list.append(tmp)
            
        # 巻数による絞り込みがあれば当てはまる事件の番号の集合を
        # 集合のリスト refined_case_number_list に登録    
        if vol_list := self.request.POST.getlist('volume'):       
            tmp = set()
            for i_case in Case.objects.all():
                vol_list_i_case = { i_chapter.volume.number for i_chapter in i_case.chapter_set.all()}
                if all([ int(j_vol) in vol_list_i_case for j_vol in vol_list]):
                    tmp.add(i_case.number)
            refined_case_number_list.append(tmp)
            
        # 登場人物による絞り込みがあれば当てはまる事件の番号の集合を
        # 集合のリスト refined_case_number_list に登録    
        if chara_list := self.request.POST.getlist('character'):       
            tmp = set()
            for i_case in Case.objects.all():
                chara_list_i_case = { i_chara.name for i_chapter in i_case.chapter_set.all()\
                     for i_chara in i_chapter.character_set.all()}
                if all([ j_chara in chara_list_i_case for j_chara in chara_list]):
                    tmp.add(i_case.number)
            refined_case_number_list.append(tmp)

        # 事件名による絞り込みがあれば当てはまる事件の番号の集合を
        # 集合のリスト refined_case_number_list に登録    
        if case_name := self.request.POST.get('case_name'):
            case_name_list = case_name.split()
            if not case_name_list:
                pass
            else:
                tmp = set()
                for i, i_case_name in enumerate(case_name_list, 1):
                    if i == 1:
                        tmp = {i_case.number for i_case in Case.objects.filter(name__contains=str(i_case_name))}
                    else:
                        tmp &= {i_case.number for i_case in Case.objects.filter(name__contains=str(i_case_name))}
                refined_case_number_list.append(tmp)
            
        # すべての絞り込みに対して積集合をとり、当てはまるものだけに
        # クエリ検索をかける。
        if refined_case_number_list:
            for i, i_refined_set in enumerate(refined_case_number_list, 1):
                if i == 1:
                    and_refined_set = i_refined_set
                else:
                    and_refined_set &= i_refined_set
            queryset = Case.objects.filter(number__in=and_refined_set)
            
        else :
            queryset = Case.objects.all()

        return queryset

    def get_context_data(self, **kwargs):
        form_list = {
            'form1': CaseKindForm(**self.get_form_kwargs()),
            'form2': VolumeForm(**self.get_form_kwargs()),
            'form3': CharaForm(**self.get_form_kwargs()),
            'form4': CaseNameForm(**self.get_form_kwargs())
        }
        kwargs.update(form_list)
        return super().get_context_data(**kwargs)

    def post(self, request, page = None):
        return self.get(request)


class CaseDetailView(DetailView):
    model = Case


class QuestionCreateView(CreateView):
    form_class = QuestionForm
    template_name = 'conan_db_app/question_form.html'
    success_url = reverse_lazy('conan_db_app:question_list')

    def form_valid(self, form):
        ''' バリデーションを通った時 '''
        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        ''' バリデーションに失敗した時 '''
        messages.warning(self.request, "保存できませんでした")
        return super().form_invalid(form)


class QuestionListView(ListView, FormMixin):
    model = Question
    template_name = 'conan_db_app/question_list.html'
    paginate_by = 3
    form_class = RefineQuestionForm
    
    def get_queryset(self):
        if self.request.POST:
            queryset = Question.objects.filter(jenre=self.request.POST['jenre'])\
                .filter(kind=self.request.POST['kind'])
        elif self.request.GET:
            queryset = Question.objects.filter(jenre=self.request.GET.get('jenre'))\
                .filter(kind=self.request.GET.get('kind'))
        else:
            queryset = Question.objects.all()
        return queryset
        
    def get_context_data(self, **kwargs):
        if self.request.POST:
            return super().get_context_data(form=self.form_class(self.request.POST))
        elif self.request.GET:
            return super().get_context_data(form=self.form_class(self.request.GET))
        else:
            return super().get_context_data()
    
    def post(self, request):
        # form = self.form_class(request.POST)
        return self.get(request)


def chara_detail_func(request, pk, page=1):
    page_num = 5
    character = Character.objects.get(id = pk)
    event = character.event_related_to.all()

    if request.method == 'POST':
        # フォームの用意
        form = WithEventForm(request.POST)

        if request.POST.get('with_event'):
            chapter_list = character.chapter.filter(event__in = event).distinct()
        else :
            chapter_list = character.chapter.all()

    # GETアクセス時の処理
    else:
        # フォームの用意
        form = WithEventForm()

        chapter_list = character.chapter.all()

    context = {
    'character' : character, # html 側で for で回すので、イテラブルとして渡す。
    'chapter_page': queryset_to_page(chapter_list, page_num, page), 
    'event_list': event,
    'form':form
    }
    return render(request, 'conan_db_app/character_detail.html', context)


def queryset_to_page(queryset, page_num, page):
    page_list = Paginator(queryset, page_num)
    return page_list.get_page(page)

templates/conan_db_app/affiliation_detail.html
{% extends "conan_db_app/base.html" %}
{% load static %}

{% block title %}組織詳細{% endblock %}

{% block main %}
<main>
    <h1>真実はいつも一つ</h1>
    <p>{{object.name}}</p>
    <table>
        <tr>
            <th>所属者</th>
            <th>役割</th>
        </tr>
        {% for i_character in object.character_set.all %}
        <tr>
            <td><a href="{% url 'conan_db_app:detail' pk=i_character.id page=1 %}">{{i_character.name}}</a></td>
            <td>
            {% for i_profession in i_character.profession.all %}
                {% if i_profession.affiliation == object %}
                    {{ i_profession.name }}
                {% endif %}
            {% endfor %}
            </td>
        </tr>
    {% endfor %}
    </table>
</main>
{% endblock %}

templates/conan_db_app/affiliation_list.html
{% extends "conan_db_app/base.html" %}
{% load static %}

{% block title %}組織一覧{% endblock %}

{% block main %}
<main>
    <h1>真実はいつも一つ</h1>
    <table>
        <tr>
            <th>名前</th>
        </tr>
    {% for affiliation in object_list %}
        <tr>
            <td><a href="{% url 'conan_db_app:affiliation_detail' pk=affiliation.id %}">{{affiliation.name}}</a></td>
        </tr>
    {% endfor %}
    </table>
</main>
{% endblock %}

templates/conan_db_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'conan_db_app/css/dist/output.css' %}"/>
    <script src="{% static 'conan_db_app/js/main.js' %}" defer></script>
    <title>{% block title %}{% endblock %}</title>
    </head>
    <body class="min-h-screen bg-amber-50 flex flex-col [&>main]:flex-1">

        {% comment %} メッセージがあればこれを出力 {% endcomment %}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        {% block main %}{% endblock %}

        <footer class="border-t-2 border-solid border-black">
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
        </footer>

        <div class="h-[50px]"></div>{% comment %} dummy フッターとフッターナビゲーションがかぶるのを防ぐため。 {% endcomment %}

        <nav class="fixed bottom-0">
            <ul class="flex [&>li]:flex-1 text-center w-screen h-[50px]
                bg-[url('/static/conan_db_app/images/bg_renga.jpg')] bg-[length:100%_1000%]
                [&>li]:border-2 [&>li]:border-solid [&>li]:border-amber-50 [&>li]:text-white [&>li]:text-2xl">
                <li><a href="{% url 'conan_db_app:list' %}    "
                        class="block h-[100%] transition-all hover:bg-white hover:text-black hover:font-bold
                                hover:opacity-30">人物</a></li>
                <li><a href="{% url 'conan_db_app:affiliation_list' %}  "
                        class="block h-[100%] transition-all hover:bg-white hover:text-black hover:font-bold
                                hover:opacity-30">組織</a></li>
                <li><a href="{% url 'conan_db_app:case_list' %}    "
                        class="block h-[100%] transition-all hover:bg-white hover:text-black hover:font-bold
                                hover:opacity-30">事件</a></li>
                <li><a href="{% url 'conan_db_app:wiseword_list' %}"
                        class="block h-[100%] transition-all hover:bg-white hover:text-black hover:font-bold
                                hover:opacity-30">名言</a></li>
            </ul>
        </nav>

    </body>
</html>

templates/conan_db_app/case_detail.html
{% extends "conan_db_app/base.html" %}
{% load static %}

{% block title %}事件詳細{% endblock %}

{% block main %}
<main>
    <h1>真実はいつも一つ</h1>
    <p>{{object.name}}</p>
    <table>
        <tr>
            <th>話数</th>
            <th>登場人物</th>
            <th>重要な出来事</th>
        </tr>
        {% for i_chapter in object.chapter_set.all|dictsort:"number_in_all" %}
        <tr>
            {% comment %} <td><a href="{% url 'conan_db_app:chapter_detail' pk=i_chapter.id %}">{{i_chapter.name}}</a></td> {% endcomment %}
            <td>{{i_chapter.volume.number}}巻 {{i_chapter.number_in_volume}}話 <a href="{% url 'conan_db_app:index' %}">{{i_chapter.name}}</a></td>
            <td>
                {% for i_character in i_chapter.character_set.all %}
                <a href="{% url 'conan_db_app:detail' pk=i_character.id %}">{{i_character.name}}</a>
                {% endfor %}
            </td>
            <td>
                {% for i_event in i_chapter.event_set.all %}
                    <ul>
                        <li>{{ i_event.content }}</li>
                    </ul>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'conan_db_app:case_list' %}">事件リストに戻る</a>
</main>
{% endblock %}

templates/conan_db_app/case_list.html
{% extends "conan_db_app/base.html" %}
{% load static %}

{% block title %}事件リスト{% endblock %}

{% block main %}
<main>
    <h1>真実はいつも一つ</h1>
    <table>
        <tr>
            <th>名前</th>
        </tr>
    {% for case in object_list %}
        <tr>
            <td> 
                <details>
                    <summary>事件{{case.number}} :<a href="{% url 'conan_db_app:case_detail' pk=case.number %}">{{case.name}}</a>
                        (
                        {% for i_chapter in case.chapter_set.all %}
                            {% ifchanged  i_chapter.volume.number %}
                                {{i_chapter.volume.number}}巻 
                            {% endifchanged %}
                        {% endfor %}
                        ) 
                        {% for i_kind in case.kind.all %}
                        < {{ i_kind.name }} >
                        {% endfor %}
                        {% for i_chapter in case.chapter_set.all|dictsort:"number_in_all" %}
                            {% if i_chapter.event_set.first %}
                                <span>*</span>
                            {% endif %}
                        {% endfor %}
                    </summary>
                    <table>
                        <tr>
                            <th>話数</th>
                            <th>登場人物</th>
                            <th>重要な出来事</th>
                        </tr>
                        {% for i_chapter in case.chapter_set.all|dictsort:"number_in_all" %}
                        <tr>
                            {% comment %} <td><a href="{% url 'conan_db_app:chapter_detail' pk=i_chapter.id %}">{{i_chapter.name}}</a></td> {% endcomment %}
                            <td>{{i_chapter.volume.number}}巻 {{i_chapter.number_in_volume}}話 {{i_chapter.name}}</td>
                            <td>
                                {% for i_character in i_chapter.character_set.all %}
                                <a href="{% url 'conan_db_app:detail' pk=i_character.id %}">{{i_character.name}}</a>
                                {% endfor %}
                            </td>
                            <td>
                                {% for i_event in i_chapter.event_set.all %}
                                <ul>
                                    <li>{{ i_event.content }}</li>
                                </ul>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>                
                </details>
            </td>
        </tr>
    {% endfor %}
    </table>
    <p>絞り込み<button><a class="text-xs" href="{% url 'conan_db_app:case_list' %}">(クリア)</a></button></p>
    <form action="{% url 'conan_db_app:case_list' %}" method="post" name="refine_form">
        {% csrf_token %}
        {% for field in form %}
            <label>
                {{ field.label }}
            </label>
            <span class="cursor-pointer" id="form0" 
                onclick="openCloseForm('form0')">＋</span>
            <div class="refine-check hidden">
                <p>{{ field }}</p>
            </div>
        {% endfor %}
        <p></p>

        {% for field in form1 %}
            <label>
                {{ field.label}}
            </label>
            <span class="cursor-pointer" id="form1" 
                onclick="openCloseForm('form1')">＋</span>
            <div class="refine-check hidden">
                {% for item in field %}
                    <p>{{ item.tag }}<label>{{ item.choice_label }}</label></p>
                {% endfor %}
            </div>
        {% endfor %}
        <p></p>

        {% for field in form2 %}
            <label>
                {{ field.label}}
            </label>
            <span class="cursor-pointer" id="form2" 
                onclick="openCloseForm('form2')">＋</span>
            <div class="refine-check hidden">
                {% for item in field %}
                    <p>{{ item.tag }}<label>{{ item.choice_label }}</label></p>
                {% endfor %}
            </div>
        {% endfor %}
        <p></p>

        {% for field in form3 %}
            <label>
                {{ field.label}}
            </label>
            <span class="cursor-pointer" id="form3" 
                onclick="openCloseForm('form3')">＋</span>
            <div class="refine-check hidden">
                {% for item in field %}
                    <p>{{ item.tag }}<label>{{ item.choice_label }}</label></p>
                {% endfor %}
            </div>
        {% endfor %}
        <p></p>

        {% for field in form4 %}
            <label>
                {{ field.label}}
            </label>
            <span class="cursor-pointer" id="form4" 
                onclick="openCloseForm('form4')">＋</span>
            <div class="refine-type hidden">
                <p>{{ field }}</p>
            </div>
        {% endfor %}
        <p></p>
        
        <button class="btn">更新</button>
    </form>
    
    <ul class="[&>li]:text-center [&>li]:text-xl [&>li]:py-2">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="javascript:plusPageAndSendForm({{1}})">
            &laquo; first</a>
        </li>
        <li class="page-item">
            <a href="javascript:plusPageAndSendForm({{page_obj.previous_page_number}})">
            &laquo; prev</a>
        </li>
    {% endif %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a href="javascript:plusPageAndSendForm({{page_obj.next_page_number}})">
            next &raquo;</a>
        </li>
        <li class="page-item">
            <a href="javascript:plusPageAndSendForm({{page_obj.paginator.num_pages}})">
            last &raquo;</a>
        </li>
    {% endif %}
    </ul>
</main>
{% endblock %}

templates/conan_db_app/character_list.html
{% extends "conan_db_app/base.html" %}
{% load static %}

{% block title %}キャラクター詳細{% endblock %}

{% block main %}
<main>
    <h1>真実はいつも一つ</h1>
    <table>
        <tr>
            <th>名前</th>
        </tr>
    {% for character in object_list %}
        <tr>
            <td><a href="{% url 'conan_db_app:detail' pk=character.id page=1 %}">{{character.name}}</a></td>
        </tr>
    {% endfor %}
    </table>
</main>
{% endblock %}